import "./globals.css";
import { playfair } from "./ui/font";

export const metadata = {
  title: "Create Personal",
  description: "Generated by create next app",
  icons: {
    icon: "/nature.avif"
  }
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${playfair.className} antialiased`}>
        {" "}
        <div>
          <h1>Navbar</h1>
        </div>
        {children}
        <div>
          <h1>Footer</h1>
        </div>
      </body>
    </html>
  );
}
